---
on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-build-${{ env.cache-name }}-
            npm-${{ runner.os }}-build-
            npm-

      - name: Install NPM dependencies
        run: npm install

      - name: Test
        run: bundle exec rspec

      - name: Lint
        run: bundle exec rubocop --parallel

      - name: Validate schema
        run: bundle exec rake schema

      - name: Build
        run: bundle exec rake build

      - name: Upload built site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: build
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: site

      # Checkout stripped-down gh-pages branch to a subdirectory, for publishing
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: tmp/publish

      - name: Publish
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          bundle exec rake publish CLONED_GH_PAGES_DIR="tmp/publish"
